language: node_js
node_js:
  - "0.12"
sudo: false

after_success:
  - $(which npm) install firebase-tools@2.0.2
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]] && [ "$TRAVIS_BRANCH" == "master" ]; then ./node_modules/firebase-tools/bin/firebase deploy --token "$FIREBASE_TOKEN"; fi
